; -----------------------------------------------
; p16f_common.inc - definitions common to all 14 bit PIC devices
;
; Copyright (C) 2005 by Raphael Neider
;
; This file is part of the SDCC/pic14 library.
; This file is licensed under the terms of the LGPL, see LGPL
; for details.
;
; $Id: p16f_common.inc 4086 2006-04-06 19:56:14Z tecodev $

		extern	STK00
		extern	STK01
		extern	STK02
		extern	STK03
		extern	STK04
		extern	STK05

